server:
  port: 8002

spring:
  servlet:
    multipart:
      max-file-size: 10MB

  application:
    name: face-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

